# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: labfgv.github.io
title: Conferência Desafio Brasil
email: labfgv@gmail.com
author: Laboratório de Políticas Públicas da FGV
description: > # "Write an awesome description for your new site here. 
  A Conferência Desafio Brasil discute o desenvolvimento do Brasil.
copyright: 'Copyright &copy; 2016 <a href="http://www.labfgv.com/">Lab FGV</a>.'
credits: 'Créditos: Landing Page by <a href="http://startbootstrap.com/">Start Bootstrap</a>; <a href="https://pages.github.com/">GitHub Pages</a>; <a href="https://jekyllrb.com/">Jekyll</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#         social          #
# ----------------------- #

social:
  - title: file-text-o
    url: http://www.labfgv.com/
  - title: facebook
    url: https://m.facebook.com/conferenciadesafiobrasil/
  - title: envelope
    url: mailto:labfgv@gmail.com?subject=[contato] conferência desafio brasil


# ----------------------- #
#          apoio          #
# ----------------------- #

parceiros:
# url tem de ter http ou https antes, ou ele interpreta como subpágina do site

#- parceiro: Instituto República
#  logo: republica.png
#  url: http://www.institutorepublica.edu.ar/
  
- parceiro: Instituto Publix
  logo: publix.png
  url: http://www.institutopublix.com.br/
  
- parceiro: Mapa Educação
  logo: mapa.png
  url: http://www.mapaeducacao.com/
  
- parceiro: FGV Social
  logo: fgv-social.png
  url: http://cps.fgv.br/
  
- parceiro: CIEB
  logo: cieb.png
  url: http://www.cieb.net.br/

- parceiro: PENSA
  logo: pensa.png
  url: http://pensa.rio/main/pensa/

- parceiro: Um Brasil
  logo: umbrasil.png
  url: http://www.umbrasil.com/

- parceiro: Centro de Liderança Públicas
  logo: clp.png
  url: http://www.clp.org.br/
  
- parceiro: EBAPE/FGV-RJ
  logo: ebape.png
  url: http://ebape.fgv.br/

- parceiro: EPGE/FGV-RJ
  logo: epge.png
  url: http://epge.fgv.br/

- parceiro: G.NOVA
  logo: gnova.png
  url: http://www.enap.gov.br/web/pt-br 

- parceiro: Ipea
  logo: ipea.png
  url: http://www.ipea.gov.br/

- parceiro: Movimento Brasil Competitivo
  logo: mbc.png
  url: http://www.mbc.org.br/mbc/novo/

- parceiro: Fundação Lemann
  logo: lemann.png
  url: http://www.fundacaolemann.org.br/

- parceiro: Sitiê
  logo: sitie.png
  url: http://www.parquesitie.org/

- parceiro: Vetor Brasil
  logo: vetorbr.png
  url: http://www.vetorbrasil.com/


# ----------------------- #
#         people          #
# ----------------------- #

people:

- name: José Mendonça Bezerra Filho
  pic: mendonca.png
  minibio: Ministro da educação, deputado federal pelo DEM-PE.
  tema: educ
  palestra: s
  social:
    - title: file-text-o
      url: portal.mec.gov.br/gabinete-do-ministro
    - title: facebook
      url: https://pt-br.facebook.com/mendoncafilhoPE/ 
      
- name: Lígia Stocche
  pic: ligia.png
  minibio: Engenheira de formação, mas ao longo da vida migrou para a educação. É fundadora e membro do conselho deliberativo do Movimento Mapa Educação e trabalha na Fundação Lemann.
  tema: educ
  palestra: n
  social:
    - title: file-text-o
      url: http://www.mapaeducacao.com/quemsomos.html
    
- name: Cláudio Lucena 
  pic: claudiol.jpg
  minibio: Pesquisador da Fundação para a Ciência e a Tecnologia de Portugal. Membro da Comunidade Octopus Cybercrime do Conselho da Europa, dos Capítulos Brasil e Portugal da Internet Societ, da International Law Association e do Comitê Internacional de Estudos sobre a Privacidade.
  tema: eco
  palestra: s
  social:
    - title: file-text-o
      url: http://www.claudiolucena.com/
    - title: linkedin
      url: https://www.linkedin.com/in/cl%C3%A1udio-lucena-8227a822

- name: Emilio Loures
  pic: maximilianol.jpg  
  minibio: Diretor de Assuntos Corporativos da Intel do Brasil. Foi gerente de planejamento e desenvolvimento de negócios da AG Telecom, sócio diretor da Miner Technology Group e consultor da Monitor/MGDK e Companhia Vale do Rio Doce.
  tema: eco
  palestra: s
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/emilio-loures-2b7175

- name: Maximiliano Salvadori Martinhão
  pic: maximilianom.png
  minibio: Secretário de Política de Informática do Ministério da Ciência, Tecnologia, Inovações e Comunicações em Campinas. Já foi Secretário de Telecomunicações no Ministério das Comunicações e Gerente Geral de Certificação e Engenharia do Espectro da ANATEL. 
  tema: eco
  palestra: s
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/maximiliano-s-martinh%C3%A3o-b1a1ab

- name: Silvio Meira
  pic: silviom.jpg
  minibio: Idealizador e fundador do C.E.S.A.R (Centro de Estudos e Sistemas Avançados do Recife. Foi assessor da secretaria de política de informática do Ministério da Ciência e Tecnologia e membro do primeiro comitê gestor da Internet/br.
  tema: eco
  palestra: s
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/silviomeira

- name: Guilherme Lichand
  pic: guilhermel.jpg
  minibio: É co-fundador da MGov-Brasil, plataforma que provê ferramentas para gestores públicos baseadas na coleta de dados através de telefone celular.
  tema: gov
  palestra: s
  social:
    - title: file-text-o
      url: http://www.mgovbrasil.com.br/
    - title: facebook
      url: https://www.facebook.com/mgovbr/ 
    - title: linkedin
      url: https://www.linkedin.com/in/guilherme-lichand-b4aa0554

- name: Gustavo Maia
  pic: gustavom.jpg
  minibio: É fundador do Colab, uma rede social para cidadania em que o usuário é capaz de fiscalizar, propor e avaliar diversos pontos da sua cidade, estado e país.
  tema: gov
  palestra: s
  social:
    - title: file-text-o
      url: http://www.colab.re/ 
    - title: facebook
      url: https://www.facebook.com/colab.re/
    - title: linkedin
      url: https://www.linkedin.com/in/gustavommaia/pt

- name: Andrei Roman
  pic: roman.png
  minibio: É fundador do Atlas Político, uma ferramenta online largamente acessível para toda a população monitorar a atuação dos políticos brasileiros e se engajar em apoio àquelas iniciativas políticas e projetos de lei que considera importantes para o país.
  tema: gov
  palestra: s
  social:
    - title: file-text-o
      url: http://www.atlaspolitico.com.br/
    - title: facebook
      url: https://www.facebook.com/atlaspolitico/
    - title: linkedin
      url: https://www.linkedin.com/in/andrei-roman-b1969a7 

- name: Guilherme de Almeida
  pic: guilhermea.png
  minibio: É diretor de Inovação da Escola Nacional de Administração Pública (Enap). Tem experiência na área de Administração Pública, com ênfase em aspectos relacionados a elaboração legislativa, participação social, política tecnológica e tecnologia para a gestão de políticas públicas.
  tema: gov
  palestra: n
  social:
    - title: file-text-o
      url: http://www.enap.gov.br/web/pt-br 
    - title: facebook
      url: https://www.facebook.com/enapgovbr/

- name: Lucia Dellagnelo
  pic: Luciap2.png
  minibio: Diretora Presidente do CIEB, é formada como Doutora e Mestre em Educação pela Universidade de Harvard. Foi Secretaria de Estado de Desenvolvimento Econômico Sustentável em Santa Catarina onde criou o Cluster de Inovação na Educação.
  tema: educ
  palestra: s
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/luciadellagnelo
    
- name: Renan Rego  
  pic: Renan.jpg
  minibio: Coordenador da Aceleração da ARTEMISIA e responsável pelas estratégias de prospecção, análise, seleção e aceleração de negócios de impacto social com modelos de negócios escaláveis em educação, saúde, serviços financeiros, habitação, água e saneamento no Brasil.
  tema: eco
  palestra: s
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/renancostarego

- name: Pedro Henrique de Cristo
  pic: pedrocristo.png  
  minibio: Fundador e Diretor Executivo do Instituto Sitiê, Pedro direciona sua carreira de designer, pesquisador e empreendedor para a integração da arquitetura com a política e a tecnologia. É também um Lemann Fellow, membro RAPS e Bolsista da Fundação Estudar.
  tema: educ
  palestra: n
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/pedro-henrique-h-f-de-cristo-97b0a722

- name: Pablo Cerdeira
  pic: pablo_cerdeira.png
  minibio: Responsável pelo PENSA – Sala de Ideias, órgão da Prefeitura do Rio de Janeiro. É advogado formado na USP, e também programador e cientista de dados. Foi Chefe de gabinete no Conselho Nacional de Justiça – CNJ e Subsecretário de Proteção e Defesa do Consumidor, na Cidade do Rio de Janeiro.
  tema: gov
  palestra: n
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/pablocerdeira
      
- name: Humberto Martins
  pic: humbertomartins.png
  minibio: Diretor do Instituto Publix. Anteriormente, ocupou posições executivas no Ministério da Administração e Reforma do Estado e no Ministério do Planejamento, Orçamento e Gestão, onde foi Secretário de Gestão.
  tema: gov
  palestra: s
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/humberto-falc%C3%A3o-martins-ma-phd-eppgg-idp-pvn-20516014
    
- name: Michael Cerqueira
  pic: michaelvetor.png
  minibio: Líder de Relacionamento com Governo no Vetor Brasil, é graduado em Administração Pública pela Fundação Getulio Vargas.
  tema: gov
  palestra: n
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/michael-cerqueira-5b330069
